const canvas=document.getElementById('game'),gl=canvas.getContext('webgl',{antialias:false,alpha:false});
if(!gl)throw new Error('WebGL qo\'llab-quvvatlanmaydi');
const $=id=>document.getElementById(id), state={running:false,x:0,y:1.1,z:10,yaw:0,pitch:-0.35,money:250000,hp:100,wanted:0,time:8,mission:0,inCar:false,run:false};
const V=`attribute vec3 p;attribute vec3 c;uniform mat4 mvp;varying vec3 v;void main(){gl_Position=mvp*vec4(p,1.);v=c;}`;
const F=`precision mediump float;varying vec3 v;uniform float light;void main(){gl_FragColor=vec4(v*light,1.);}`;
function shader(t,s){const q=gl.createShader(t);gl.shaderSource(q,s);gl.compileShader(q);if(!gl.getShaderParameter(q,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(q));return q}
const pr=gl.createProgram();gl.attachShader(pr,shader(gl.VERTEX_SHADER,V));gl.attachShader(pr,shader(gl.FRAGMENT_SHADER,F));gl.linkProgram(pr);if(!gl.getProgramParameter(pr,gl.LINK_STATUS))throw Error('Shader link xatosi');gl.useProgram(pr);
const loc={p:gl.getAttribLocation(pr,'p'),c:gl.getAttribLocation(pr,'c'),mvp:gl.getUniformLocation(pr,'mvp'),light:gl.getUniformLocation(pr,'light')};
const cube=[];function box(x,y,z,sx,sy,sz,c){const x0=x-sx/2,x1=x+sx/2,y0=y,y1=y+sy,z0=z-sz/2,z1=z+sz/2;const v=[[x0,y0,z0],[x1,y0,z0],[x1,y1,z0],[x0,y1,z0],[x0,y0,z1],[x1,y0,z1],[x1,y1,z1],[x0,y1,z1]],f=[[0,1,2,3],[5,4,7,6],[4,0,3,7],[1,5,6,2],[3,2,6,7],[4,5,1,0]];for(const a of f){for(let i=1;i<3;i++)for(const j of [0,i,i+1]){const q=v[a[j]];cube.push(...q,...c)}}}
box(0,-.15,0,100,.2,100,[.18,.24,.27]);
for(let x=-45;x<=45;x+=10){for(let z=-45;z<=45;z+=10){if(Math.abs(x)<5||Math.abs(z)<5)continue;const h=3+((Math.abs(x*13+z*7)%8));box(x,h/2,z,7,h,7,[.25+.03*(h%3),.32+.02*(h%4),.4+.02*(h%2)]);}}
for(let x=-45;x<=45;x+=10){box(x,.03,0,4,.04,100,[.08,.09,.1])}for(let z=-45;z<=45;z+=10){box(0,.035,z,100,.04,4,[.08,.09,.1])}
box(0,.15,0,4,.25,100,[.75,.65,.25]);box(0,.16,0,100,.25,4,[.75,.65,.25]);
const verts=new Float32Array(cube),pb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.bufferData(gl.ARRAY_BUFFER,verts,gl.STATIC_DRAW);gl.enableVertexAttribArray(loc.p);gl.vertexAttribPointer(loc.p,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(loc.c);gl.vertexAttribPointer(loc.c,3,gl.FLOAT,false,24,12);
function mat(){const a=new Float32Array(16);a[0]=a[5]=a[10]=a[15]=1;return a}function mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}function persp(f,asp,n,fa){const q=1/Math.tan(f/2),o=new Float32Array(16);o[0]=q/asp;o[5]=q;o[10]=(fa+n)/(n-fa);o[11]=-1;o[14]=2*fa*n/(n-fa);return o}function view(){const cy=Math.cos(state.yaw),sy=Math.sin(state.yaw),cp=Math.cos(state.pitch),sp=Math.sin(state.pitch),o=mat();o[0]=cy;o[2]=-sy;o[5]=cp;o[6]=sp;o[8]=sy*cp;o[10]=cy*cp;o[12]=-(o[0]*state.x+o[8]*state.z);o[13]=-state.y;o[14]=-(o[2]*state.x+o[10]*state.z);return o}
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(e.key==='Shift')state.run=true});addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=0;if(e.key==='Shift')state.run=false});
let joy={x:0,y:0,active:false};const stick=$('stick'),knob=document.createElement('div');knob.id='knob';knob.className='knob';stick.appendChild(knob);function joyMove(e){const r=stick.getBoundingClientRect(),p=e.touches?e.touches[0]:e,x=p.clientX-r.left-r.width/2,y=p.clientY-r.top-r.height/2,d=Math.hypot(x,y),m=r.width*.42,k=Math.min(1,d/m);joy.x=(d?x/d:0)*k;joy.y=(d?y/d:0)*k;knob.style.transform=`translate(${joy.x*35}px,${joy.y*35}px)`}stick.addEventListener('pointerdown',e=>{joy.active=true;stick.setPointerCapture(e.pointerId);joyMove(e)});stick.addEventListener('pointermove',e=>joy.active&&joyMove(e));stick.addEventListener('pointerup',()=>{joy.active=false;joy.x=joy.y=0;knob.style.transform=''});
$('run').onpointerdown=()=>state.run=true;$('run').onpointerup=()=>state.run=false;
$('enter').onclick=()=>{state.inCar=!state.inCar;$('enter').textContent=state.inCar?'🚶':'🚗';$('missionText').textContent=state.inCar?'Mashina bilan markazga boring.':'Markazga boring.'};
$('action').onclick=()=>{if(state.mission===0){state.mission=1;state.money+=50000;$('money').textContent=state.money.toLocaleString('uz-UZ');$('missionText').textContent='Yangi topshiriq: ish joyiga yetib boring.'}else{$('dialog').classList.remove('hidden');$('dialogText').textContent='Mahalliy AI: Assalomu alaykum! UZB ROLE dunyosida ish, uy, transport va qonun-qoidalar sizning qarorlaringizga bog\'liq.'}};
$('dialogBtn').onclick=()=>$('dialog').classList.add('hidden');
function move(dt){let f=-joy.y||((keys.w?1:0)-(keys.s?1:0)),r=joy.x||((keys.d?1:0)-(keys.a?1:0));if(!f&&!r)return;const speed=(state.inCar?9:4.2)*(state.run?1.55:1);state.x+=(Math.sin(state.yaw)*f+Math.cos(state.yaw)*r)*speed*dt;state.z+=(Math.cos(state.yaw)*f-Math.sin(state.yaw)*r)*speed*dt;state.x=Math.max(-48,Math.min(48,state.x));state.z=Math.max(-48,Math.min(48,state.z));}
function resize(){const d=Math.min(devicePixelRatio||1,1.5),w=innerWidth*d,h=innerHeight*d;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}}
function hud(){state.time=(state.time+0.0015)%24;$('clock').textContent=String(Math.floor(state.time)).padStart(2,'0')+':'+String(Math.floor((state.time%1)*60)).padStart(2,'0');$('hp').textContent=Math.max(0,Math.floor(state.hp));$('wanted').textContent=state.wanted;$('money').textContent=Math.floor(state.money).toLocaleString('uz-UZ')}
let last=performance.now();function frame(now){if(!state.running)return;const dt=Math.min(.033,(now-last)/1000);last=now;resize();move(dt);hud();const asp=canvas.width/canvas.height,P=persp(1.05,asp,.1,150),M=mul(P,view());gl.clearColor(.03,.07,.12,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.uniformMatrix4fv(loc.mvp,false,M);const light=.55+.45*Math.max(0,Math.sin((state.time-6)/24*Math.PI*2));gl.uniform1f(loc.light,light);gl.drawArrays(gl.TRIANGLES,0,verts.length/6);requestAnimationFrame(frame)}
$('play').onclick=()=>{$('start').remove();state.running=true;requestAnimationFrame(frame)};
addEventListener('resize',resize);resize();
