const http=require('http');const fs=require('fs');const path=require('path');const https=require('https');
const root=path.resolve(__dirname,'app');
const three=path.join(root,'three.min.js');
const urls=['https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.min.js','https://unpkg.com/three@0.179.1/build/three.min.js'];
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml'};
function download(url,cb){https.get(url,{headers:{'User-Agent':'Samarqand-Soya'}},r=>{if([301,302,307,308].includes(r.statusCode)&&r.headers.location){r.resume();return download(r.headers.location,cb)}if(r.statusCode!==200){r.resume();return cb(new Error('HTTP '+r.statusCode))}const w=fs.createWriteStream(three);r.pipe(w);w.on('finish',()=>w.close(()=>cb(null)))}).on('error',cb)}
function ensureThree(cb){if(fs.existsSync(three)&&fs.statSync(three).size>100000)return cb(null);let i=0;const next=()=>i<urls.length?download(urls[i++],e=>e?next():cb(null)):cb(new Error('Three.js download failed'));next()}
function send404(r){r.writeHead(404);r.end('Not found')}function send500(r){r.writeHead(500);r.end('Server error')}
function sendFile(r,f){fs.stat(f,(e,s)=>{if(e)return send404(r);if(s.isDirectory()){const x=path.join(f,'index.html');return fs.access(x,e=>e?send404(r):sendFile(r,x))}fs.readFile(f,(e,d)=>{if(e)return send500(r);r.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream','Cache-Control':'no-store'});r.end(d)})})}
const server=http.createServer((req,res)=>{try{let u=decodeURIComponent(new URL(req.url||'/',`http://${req.headers.host||'localhost'}`).pathname);if(u==='/')u='/index.html';if(u==='/three.min.js'&&!fs.existsSync(three))return ensureThree(e=>e?send500(res):sendFile(res,three));const f=path.resolve(root,u.replace(/^\/+/,''));if(f!==root&&!f.startsWith(root+path.sep)){res.writeHead(403);return res.end('Forbidden')}sendFile(res,f)}catch(e){send500(res)}});
const port=Number(process.env.PORT)||3000;server.listen(port,'0.0.0.0',()=>console.log(`Samarqand Drive running on http://127.0.0.1:${port}`));